### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CAP_PROP_FRAME_WIDTH'

### ISSUE THREAD

**Issue by kenkroft** [memo/webcam-pix2pix-tensorflow#2]
Hello,

First of all thanks for this amazing piece of code.

I got this problem though : 

Traceback (most recent call last):
  File "webcam-pix2pix.py", line 74, in <module>
    capture = init_capture(capture, output_shape=predictor.input_shape)
  File "webcam-pix2pix.py", line 63, in init_capture
    output_shape = output_shape
  File "/home/corepan/Desktop/webcam-pix2pix-tensorflow-master/msa/capturer.py", line 31, in __init__
    self.cvcap.set(cv2.CAP_PROP_FRAME_WIDTH, capture_shape[1])
AttributeError: 'module' object has no attribute 'CAP_PROP_FRAME_WIDTH'

Would you have an idea of what this could be ?

Thank so much.

**Comment by memoakten** [comment]
yes this usually happens when opencv can't find a camera. Do you have a webcam?

Alternatively, what version of opencv are you using?

**Comment by bjoernkarmann** [comment]
Hi memo, I have the same problem. I am using python2 and OpenCV 2. Any idea how fix it?

In my case, the GUI opens for 3 seconds and then it crashes with the same error as above: 
```
AttributeError: 'module' object has no attribute 'CAP_PROP_FRAME_WIDTH'
Cleaned up camera.
```
